apiVersion: v1
kind: Service
metadata:
  name: cartapp-service
spec:
  selector:
    app: cartapp
  ports:
    - protocol: TCP
      port: 80       # Port exposed externally
      targetPort: 8080 # Port your Spring Boot app runs on
  type: LoadBalancer # Use 'NodePort' if you are testing locally on Minikube